name: Remove Folder from Checked-Out Code

on:
 workflow_dispatch:
   inputs:
     ENVIRONMENT:
       default: "prod"
     APP_NAME:
       default: "myapp"
     VERSION:
       default: "version2"
   

jobs:       
  remove_folder1:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Folder
        run: |
          touch test2023.txt
          echo "test2023content" >> test2023.txt
          ls
          cat test2023.txt


