name: Remove Folder from Checked-Out Code

on:
 workflow_dispatch:
   inputs:
     ENVIRONMENT:
       default: "prod"
     APP_NAME:
       default: "myapp"
     VERSION:
       default: "version2"
     CHG_DES:
       default: ${{inputs.APP_NAME}} in ${{inputs.ENVIRONMENT}} with ${{inputs.VERSION}}
   

jobs:
  remove_folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Remove Folder
        run: |
            echo ${{CHG_DES}}
            #echo "${{inputs.APP_NAME}} in ${{inputs.ENVIRONMENT}} with ${{inputs.VERSION}}" 

