name: Remove Folder from Checked-Out Code

on:
 workflow_dispatch:
   inputs:
     ENVIRONMENT:
       default: "prod"
     APP_NAME:
       default: "myapp"
     VERSION:
       default: "version2"
   

jobs:
  remove_folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Remove Folder
        run: |            
            my_var=$(echo "Hello, World!")
            echo $my_var

