name: Remove Folder from Checked-Out Code

on:
 workflow_dispatch

jobs:
  remove_folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Remove Folder
        run: |
          ls
          if [ -d src/test ]; then   
            rm -rf src/test
          else
            echo "no folder exists"
          fi
          echo "after remove"
          ls
          cd src
          ls

