name: Remove Folder from Checked-Out Code

on:
 workflow_dispatch:
   inputs:
     ENVIRONMENT:
       default: "prod"
     APP_NAME:
       default: "myapp"
     VERSION:
       default: "version2"
   

jobs:
  remove_folder:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variable
        id: set_variable
        run: |
          echo "::set-output name=my_var::$(echo Deployment of ${{inputs.APP_NAME}} in ${{inputs.ENVIRONMENT}} with ${{inputs.VERSION}})"

      - name: Remove Folder
        run: |
          echo ${{steps.set_variable.outputs.my_var}}
          
  remove_folder1:
    needs: remove_folder
    runs-on: ubuntu-latest
    steps:
      - name: Remove Folder
        run: |
          echo ${{needs.removefolder.set_variable.outputs.my_var}}          


