name: "SIMPLE"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:   
      - name: checkut code
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: ls

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
          
      - name: Check versions
        run: java -version
        
      - name: Run a one-line script
        run: java src/samplecode.java        

